@startuml

title Mail Verifier logic

start
if (sender is in white list?) then (yes)
  #green:**forward**;
  stop
else (no)
  if (at least one recipient is a customer?) then (no)
  	#green:**forward**;
  	stop
  else (yes)
  	if (all recipients belong to the same customer \nor a white-list domain?) then (no)
  		#red:**bounce**;
  		note left: customers mix\nor mix of customer and non-customer
  		stop
  	else (yes)
  		if (message has attachments?) then (no)
  			#green:**forward**;
  			stop
  		else (yes)
  			if (all attachments names begin with customer code \nor match special regular expression?) then (yes)
  				#green:**forward**;
  				stop
  			else (no)
  				#red:**bounce**;
  				note left: attachment-customer mismatch
  				stop
@enduml