@startuml

title Relevant servers in managemnet-network

actor workstation
component verifier as [mail-verifiter.beeriprint.co.il \n outbound proxy or something]
component exchange as [mailsrv.beeriprint.co.il \n MS Exchange Server]
component mcafee as [mail.beeriprint.co.il \n McAfee Email Gateway]
component www as [WWW, The Internet]

workstation -> exchange
exchange --> verifier: connector
verifier --> workstation: bonce
verifier --> mcafee: forward
mcafee --> [www]

@enduml
