SELECT DISTINCT(job_name) FROM BATCH_JOB_INSTANCE;

SELECT JOB_EXECUTION_ID, JOB_NAME, START_TIME, END_TIME, STATUS
FROM BATCH_JOB_INSTANCE, BATCH_JOB_EXECUTION
WHERE BATCH_JOB_INSTANCE.JOB_INSTANCE_ID = BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
ORDER BY START_TIME;

SELECT * FROM BATCH_JOB_EXECUTION_PARAMS WHERE JOB_EXECUTION_ID = 1;

SELECT STEP_NAME, READ_COUNT, WRITE_COUNT, COMMIT_COUNT, STATUS
FROM BATCH_STEP_EXECUTION 
WHERE JOB_EXECUTION_ID = 1;